# Generated by Django 4.0.3 on 2022-03-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_category_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=150, null=True, verbose_name='Kitap Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created',
            field=models.DateTimeField(verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Yazar İsmi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author', verbose_name='Yazar İsmi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='Kategori İsmi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Kitap İsmi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ürün Fiyatı'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Kategori İsmi'),
        ),
    ]
