# Generated by Django 4.0.3 on 2022-03-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_author_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.IntegerField(auto_created=False,help_text='primary key', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Website Title')),
                ('description', models.CharField(max_length=160, verbose_name='Website Description')),
                ('logo', models.CharField(max_length=150, verbose_name='Website Logo')),
                ('favicon', models.CharField(max_length=150, verbose_name='Website Favicon')),
            ],
        ),
    ]
